export const fileExtensionsToLanguageMap = {
  ".adb": "Ada",
  ".ads": "Ada",
  ".ada": "Ada",
  ".asm": "Assembly",
  ".s": "Assembly",
  ".awk": "AWK",
  ".bat": "Batch",
  ".cmd": "Batch",
  ".bash": "Bash",
  ".sh": "Shell",
  ".zsh": "Zsh",
  ".ksh": "KornShell",
  ".fish": "Fish Shell",
  ".c": "C",
  ".h": "C",
  ".cil": "CIL",
  ".clj": "Clojure",
  ".cljc": "Clojure",
  ".cljs": "ClojureScript",
  ".coffee": "CoffeeScript",
  ".cr": "Crystal",
  ".cpp": "C++",
  ".cxx": "C++",
  ".cc": "C++",
  ".hpp": "C++",
  ".hh": "C++",
  ".hxx": "C++",
  ".cs": "C#",
  ".d": "D",
  ".dart": "Dart",
  ".el": "Emacs Lisp",
  ".ex": "Elixir",
  ".exs": "Elixir",
  ".erl": "Erlang",
  ".hrl": "Erlang",
  ".f": "Fortran",
  ".for": "Fortran",
  ".f90": "Fortran",
  ".f95": "Fortran",
  ".f03": "Fortran",
  ".fs": "F#",
  ".fsx": "F#",
  ".fsi": "F#",
  ".gd": "GDScript",
  ".go": "Go",
  ".groovy": "Groovy",
  ".hs": "Haskell",
  ".hx": "Haxe",
  ".java": "Java",
  ".jl": "Julia",
  ".js": "JavaScript",
  ".mjs": "JavaScript",
  ".md": "Markdown",
  ".cjs": "JavaScript",
  ".jsx": "JavaScript",
  ".json": "JSON",
  ".kt": "Kotlin",
  ".kts": "Kotlin Script",
  ".lisp": "Common Lisp",
  ".lsp": "Common Lisp",
  ".cl": "Common Lisp",
  ".l": "Lex",
  ".lex": "Lex",
  ".lua": "Lua",
  ".m": "Objective-C",
  ".mm": "Objective-C++",
  ".mojo": "Mojo",
  ".nim": "Nim",
  ".nims": "Nim Script",
  ".ml": "OCaml",
  ".mli": "OCaml",
  ".php": "PHP",
  ".pl": "Perl",
  ".pm": "Perl Module",
  ".ps1": "PowerShell",
  ".psm1": "PowerShell Module",
  ".psd1": "PowerShell Data",
  ".purs": "PureScript",
  ".py": "Python",
  ".pyw": "Python",
  ".qs": "Q#",
  ".r": "R",
  ".raku": "Raku",
  ".rakumod": "Raku Module",
  ".p6": "Raku",
  ".pm6": "Raku Module",
  ".rb": "Ruby",
  ".rs": "Rust",
  ".scala": "Scala",
  ".sc": "Scala Script",
  ".scm": "Scheme",
  ".ss": "Scheme",
  ".sql": "SQL",
  ".swift": "Swift",
  ".tcl": "Tcl",
  ".tsx": "TypeScript",
  ".ts": "TypeScript",
  ".vala": "Vala",
  ".vapi": "Vala API",
  ".vb": "Visual Basic .NET",
  ".vbs": "VBScript",
  ".wat": "WebAssembly",
  ".wast": "WebAssembly",
  ".zig": "Zig"
}
